using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SecretSanta.Data.Models
{
    public class SecretSantaContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Present> Presents { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite(@"Data Source=SecretSantaDB.db");
            // AUTOGENERATED ?? base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().ToTable("Users");
            modelBuilder.Entity<Present>().ToTable("Presents");
            // AUTOGENERATED ?? base.OnModelCreating(modelBuilder);
        }
    }
    
    public class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public virtual List<Present> Presents { get; } = new List<Present>();
    }
    
    public class Present
    {
       public int PresentId { get; set; } 
       public DateTime Date { get; set; }
       
       public string Url { get; set; }
       public string Price { get; set; }
       public byte[] Image { get; set; }
       
       [ForeignKey("UserId")]
       public virtual User User { get; set; }
    }
}